#
###################################
# Site wide configuration
####################################
#
title:       "Robert Lovelock"
description: 'Technical Architect. Working at BlackSwan.com in Exeter, UK.'
url:         http://roblovelock.com

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/London
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Robert Lovelock
  avatar: avatar.jpg
  job: "Technical Architect"
  bio: ""
  email: rob@roblovelock.com
  disqus-shortname: 
  twitter: roblovelock
  facebook: roblovelock
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: roblovelock
  stackoverflow: 1440855/roblovelock #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: roblovelock #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

theme: jekyll-theme-midnight
